In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

import sklearn

# 1.데이터 준비

### 1.1 데이터 불러오기

In [3]:
df = pd.read_csv('../data/SeoulBikeData_labeling_fin.csv', encoding='cp949')
df

Date  Year  Month  Day  Rented Bike Count  Hour  Temperature(℃)  \
0     2017-12-01  2017     12    1                254     0            -5.2   
1     2017-12-01  2017     12    1                204     1            -5.5   
2     2017-12-01  2017     12    1                173     2            -6.0   
3     2017-12-01  2017     12    1                107     3            -6.2   
4     2017-12-01  2017     12    1                 78     4            -6.0   
...          ...   ...    ...  ...                ...   ...             ...   
8755  2018-11-30  2018     11   30               1003    19             4.2   
8756  2018-11-30  2018     11   30                764    20             3.4   
8757  2018-11-30  2018     11   30                694    21             2.6   
8758  2018-11-30  2018     11   30                712    22             2.1   
8759  2018-11-30  2018     11   30                584    23             1.9   

      Humidity(%)  Wind speed (m/s)  Visibility (10m)  \
0              37               2.2              2000   
1              38               0.8              2000   
2              39               1.0              2000   
3              40               0.9              2000   
4              36               2.3              2000   
...           ...               ...               ...   
8755           34               2.6              1894   
8756           37               2.3              2000   
8757           39               0.3              1968   
8758           41               1.0              1859   
8759           43               1.3              1909   

      Dew point temperature(℃)  Solar Radiation (MJ/m2)  Rainfall(mm)  \
0                        -17.6                      0.0           0.0   
1                        -17.6                      0.0           0.0   
2                        -17.7                      0.0           0.0   
3                        -17.6                      0.0           0.0   
4                        -18.6                      0.0           0.0   
...                        ...                      ...           ...   
8755                     -10.3                      0.0           0.0   
8756                      -9.9                      0.0           0.0   
8757                      -9.9                      0.0           0.0   
8758                      -9.8                      0.0           0.0   
8759                      -9.3                      0.0           0.0   

      Snowfall (cm) Seasons     Holiday Functioning Day  
0               0.0  Winter  No Holiday             Yes  
1               0.0  Winter  No Holiday             Yes  
2               0.0  Winter  No Holiday             Yes  
3               0.0  Winter  No Holiday             Yes  
4               0.0  Winter  No Holiday             Yes  
...             ...     ...         ...             ...  
8755            0.0  Autumn  No Holiday             Yes  
8756            0.0  Autumn  No Holiday             Yes  
8757            0.0  Autumn  No Holiday             Yes  
8758            0.0  Autumn  No Holiday             Yes  
8759            0.0  Autumn  No Holiday             Yes  

[8760 rows x 17 columns]

### 1.2 날짜 데이터 형식 변환하기

In [4]:
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

### 1.3 범주형 데이터를 더미변수로 변경하기

In [5]:
df = pd.get_dummies(df, columns=['Seasons', 'Holiday', 'Functioning Day'])
df

Date  Year  Month  Day  Rented Bike Count  Hour  Temperature(℃)  \
0    2017-12-01  2017     12    1                254     0            -5.2   
1    2017-12-01  2017     12    1                204     1            -5.5   
2    2017-12-01  2017     12    1                173     2            -6.0   
3    2017-12-01  2017     12    1                107     3            -6.2   
4    2017-12-01  2017     12    1                 78     4            -6.0   
...         ...   ...    ...  ...                ...   ...             ...   
8755 2018-11-30  2018     11   30               1003    19             4.2   
8756 2018-11-30  2018     11   30                764    20             3.4   
8757 2018-11-30  2018     11   30                694    21             2.6   
8758 2018-11-30  2018     11   30                712    22             2.1   
8759 2018-11-30  2018     11   30                584    23             1.9   

      Humidity(%)  Wind speed (m/s)  Visibility (10m)  ...  Rainfall(mm)  \
0              37               2.2              2000  ...           0.0   
1              38               0.8              2000  ...           0.0   
2              39               1.0              2000  ...           0.0   
3              40               0.9              2000  ...           0.0   
4              36               2.3              2000  ...           0.0   
...           ...               ...               ...  ...           ...   
8755           34               2.6              1894  ...           0.0   
8756           37               2.3              2000  ...           0.0   
8757           39               0.3              1968  ...           0.0   
8758           41               1.0              1859  ...           0.0   
8759           43               1.3              1909  ...           0.0   

      Snowfall (cm)  Seasons_Autumn  Seasons_Spring  Seasons_Summer  \
0               0.0               0               0               0   
1               0.0               0               0               0   
2               0.0               0               0               0   
3               0.0               0               0               0   
4               0.0               0               0               0   
...             ...             ...             ...             ...   
8755            0.0               1               0               0   
8756            0.0               1               0               0   
8757            0.0               1               0               0   
8758            0.0               1               0               0   
8759            0.0               1               0               0   

      Seasons_Winter  Holiday_Holiday  Holiday_No Holiday  Functioning Day_No  \
0                  1                0                   1                   0   
1                  1                0                   1                   0   
2                  1                0                   1                   0   
3                  1                0                   1                   0   
4                  1                0                   1                   0   
...              ...              ...                 ...                 ...   
8755               0                0                   1                   0   
8756               0                0                   1                   0   
8757               0                0                   1                   0   
8758               0                0                   1                   0   
8759               0                0                   1                   0   

      Functioning Day_Yes  
0                       1  
1                       1  
2                       1  
3                       1  
4                       1  
...                   ...  
8755                    1  
8756                    1  
8757                    1  
8758                    1  
8759                    1  

# 2.데이터 분할

### 2.1 데이터 분할하기

In [17]:
X = df.drop(['Date', 'Year', 'Month', 'Day', 'Rented Bike Count'], axis=1)
y = df['Rented Bike Count']

In [18]:
X = np.array(X)
y = np.array(y)
X, y

(array([[ 0. , -5.2, 37. , ...,  1. ,  0. ,  1. ],
        [ 1. , -5.5, 38. , ...,  1. ,  0. ,  1. ],
        [ 2. , -6. , 39. , ...,  1. ,  0. ,  1. ],
        ...,
        [21. ,  2.6, 39. , ...,  1. ,  0. ,  1. ],
        [22. ,  2.1, 41. , ...,  1. ,  0. ,  1. ],
        [23. ,  1.9, 43. , ...,  1. ,  0. ,  1. ]]),
 array([254, 204, 173, ..., 694, 712, 584]))

# 3. 교차검증

### 3.1 라이브러리 임포트

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold

from sklearn.metrics import r2_score

from sklearn.model_selection import train_test_split

### 3.2 모델 

In [20]:
lr = LinearRegression()

In [21]:
kfold = KFold(5)
list(kfold.split(X))

[(array([1752, 1753, 1754, ..., 8757, 8758, 8759]),
  array([   0,    1,    2, ..., 1749, 1750, 1751])),
 (array([   0,    1,    2, ..., 8757, 8758, 8759]),
  array([1752, 1753, 1754, ..., 3501, 3502, 3503])),
 (array([   0,    1,    2, ..., 8757, 8758, 8759]),
  array([3504, 3505, 3506, ..., 5253, 5254, 5255])),
 (array([   0,    1,    2, ..., 8757, 8758, 8759]),
  array([5256, 5257, 5258, ..., 7005, 7006, 7007])),
 (array([   0,    1,    2, ..., 7005, 7006, 7007]),
  array([7008, 7009, 7010, ..., 8757, 8758, 8759]))]

In [22]:
r2_scores = []

for train_idx, test_idx in kfold.split(X):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    
    reg = lr.fit(X_train, y_train)
    y_pred = reg.predict(X_test)
    y_pred[y_pred < 0] = 0.
    
    r2 = r2_score(y_test, y_pred)
    r2_scores.append(r2)

In [23]:
r2_scores

[-1.21758702875037,
 0.17844906573736996,
 0.24893756360651287,
 -0.08154391987952891,
 0.5717370649436059]

In [24]:
for i, r2 in enumerate(r2_scores):
    print(i+1, f'- R2 = {r2:.3f}')
    
print(f'average R2 = {np.round(np.mean(r2_scores),3)}')

1 - R2 = -1.218
2 - R2 = 0.178
3 - R2 = 0.249
4 - R2 = -0.082
5 - R2 = 0.572
average R2 = -0.06
